[INJICERT-641] add Certify postgres dataprovider plugin
mosip/artifactory-ref-impl pull request #1003
Opened 2024-11-26 17:35 UTC by vharsh

2024-11-26 17:42 UTC, vharsh commented
The above changeset is failing as the postgres plugin isn't merged to `develop` yet.

```
Error: ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.5.0:copy (copy) on project artifactory-parent: Unable to find/resolve artifact.: Could not find artifact io.mosip.certify:postgres-dataprovider-plugin:jar:0.3.0-SNAPSHOT in ossrh (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
```

2024-11-27 06:22 UTC, vishwa-vyom requested changes

2024-11-27 06:22 UTC, vishwa-vyom commented on artifacts/pom.xml
> +<!-- artifactItem section for certify mock ida dataprovider plugin -->
comment is confusing, what is the direct relevance to mock ida here ?

2024-11-27 06:22 UTC, vishwa-vyom commented on artifacts/pom.xml
> -		<certify-plugin.location>/usr/share/nginx/html/artifactory/libs-release-local/certify/certify-plugin</certify-plugin.location>
why is this line removed ?

2024-11-27 06:22 UTC, vishwa-vyom commented on artifacts/pom.xml
> +        <certify-mock-ida-dataprovider-plugin.fileName>certify-mock-ida-dataprovider-plugin.jar</certify-mock-ida-dataprovider-plugin.fileName>
All mocks to be part of the mock-certify-plugin, why do we have a different entry called certify-mock-ida-dataprovider-plugin.jar ?

2024-11-27 07:50 UTC, vishwa-vyom commented on artifacts/pom.xml
> +        <certify-mock-ida-dataprovider-plugin.fileName>certify-mock-ida-dataprovider-plugin.jar</certify-mock-ida-dataprovider-plugin.fileName>
@vharsh Is suppose to create a bug for this and attach to this comment, marking it resolved for now.

2024-11-27 07:51 UTC, vishwa-vyom approved these changes

2024-11-27 07:51 UTC, merged

2024-11-27 07:52 UTC, vishwa-vyom commented on artifacts/pom.xml
> +        <certify-mock-ida-dataprovider-plugin.fileName>certify-mock-ida-dataprovider-plugin.jar</certify-mock-ida-dataprovider-plugin.fileName>
https://mosip.atlassian.net/browse/INJICERT-643