Moved Artifactory changes from develop to release 1.3.x for PMP
mosip/artifactory-ref-impl pull request #908
Opened 2024-08-27 08:20 UTC by GOKULRAJ136

2024-08-27 12:18 UTC, dhanendra06 approved these changes

2024-08-28 12:47 UTC, aranaravi requested changes
Is the respective file changes are already committed because the input type change will impact the actual functionality.

2024-08-28 12:53 UTC, GOKULRAJ136 commented
> Is the respective file changes are already committed because the input type change will impact the actual functionality.

This is the fix for a critical bug that has been committed to the develop branch and tested; therefore, we are proceeding to merge it into the release-1.3.x branch.

2024-08-28 12:56 UTC, aranaravi approved these changes

2024-09-24 13:44 UTC, aranaravi approved these changes

2024-09-24 14:42 UTC, Prafulrakhade approved these changes

2024-09-24 14:42 UTC, merged